import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import AuthModal from "@/components/AuthModal";
import Providers from "./providers";

const vietnam_pro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={vietnam_pro.className}>
          <Header />
          <main>
            <AuthModal />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
